site_name: Svelte Web Components
site_url: https://panos-stavrianos.github.io/svelte_web_components
repo_url: https://github.com/panos-stavrianos/svelte_web_components
repo_name: panos-stavrianos/svelte_web_components
site_author: Panos Stavrianos
site_description: A way to use Svelte Web Components from python without a build step

theme:
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  font:
    text: Nunito
  features:
    - navigation.instant
    - navigation.tracking
    - header.autohide
    - navigation.top
    - content.code.copy

  palette:
    - scheme: default
      primary: deep blue
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: deep blue
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to system preference
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://orbitsystems.gr
      name: Find us on the web
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/orbitsystems.gr
      name: Find us on Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/orbit.systems/
      name: Find us on Instagram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/orbit-systems-greece
      name: Find us on LinkedIn
  generator: false

copyright: Copyright © 2023 Orbit Systems

plugins:
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.details
  - admonition
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - stylesheets/extra.css

nav:
  - 'index.md'
  - 'usage.md'
  - 'components.md'
  - 'bundle.md'
  - 'fastapi_integration.md'
  - 'contribute.md'
